name: Friday Team Colour

on:
  schedule:
    - cron: "0 9 * * 2"
  workflow_dispatch:

jobs:
  post-colour:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Post colour
        run: node colours.js
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}